spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/excel-db
    username: postgres
    password: rashid

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090
